{% set version = "0.5.0" %}

package:
  name: inflection
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/inflection/inflection-{{ version }}.tar.gz
  sha256: f576e85132d34f5bf7df5183c2c6f94cfb32e528f53065345cf71329ba0b8924

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - inflection

about:
  home: https://github.com/jpvanhal/inflection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A port of Ruby on Rails inflector to Python
  dev_url: https://github.com/jpvanhal/inflection
  doc_url: https://inflection.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - abloemert
