{% set version = "0.4.0" %}

package:
  name: inflection
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/inflection/inflection-{{ version }}.tar.gz
  sha256: 32a5c3341d9583ec319548b9015b7fbdf8c429cbcb575d326c33ae3a0e90d52c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - inflection

about:
  home: https://github.com/jpvanhal/inflection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A port of Ruby on Rails inflector to Python
  dev_url: https://github.com/jpvanhal/inflection
  doc_url: https://inflection.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - abloemert
