# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cxj9JUtNaeAHBgs32wLr4oD3EOx2tAfVR0DmMASqubQL+Ef8DTSM3XXwGwy57hAEOWEr2lEtc75Ffq8G93pFvyQf8Uu6s65YRw1o4Fsj2USLWoz5Q2NAdIkdRpWUpRtUGVm4l50KuVDz4Q/h5LmYGm4auEl5bbE8KOzXX0NDgGynckSJ1RZXWZSTynXTG+91fAD8FEkndPXyrsDNNCUXchPu0stXEqvbHpu/HhRA6AZnOrVNU8Z1+Df9IDRpAYEhPPlwqfih85LjCkvuFJwocyc18zoUTdilXBmUzhCqpXUBFDHZkQ1qejlvjYXkMqt4eP2oGoTI4XAGwDB1pDf11o2uDS0NLpc/LU1Lph4K3WXP8JEENsFNjqchQYYenfI+m6knxft+3aGPEeSRYJu9p0jM+ktXZ0RXAlcSiYaUVyhOvsM2NnhJOhvlT/mrWCwembR/L8dthHQGd6OGKW3CGWpCD5cBmiIAV/UZ32Mo7wjfSnihguiO3q1TpzHUGWGqUqJveCec52mGuC0PaeZXct3Dh0nbB5HXs4sQOGTlkX/lJjwPYxQP6tVA8FzxZH/rjP7VWDf1xo+q+aDtdzmaMHcwKf7BXBh87w/wulG6J+VVwrhYuts0fqYCg8FcM94gIuQeQMuSQZrz6qXLKvQZ2PqmPzMRVMl92rYhObzq17o="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
